In [1]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

In [3]:
data = pd.read_csv('C:\\Users\\ivcbibl13\\Documents\\Jupyter\\BankChurners.csv')
data_sel = data.dropna()

In [4]:
le = LabelEncoder()
data_sel['Gender'] = np.where(data_sel['Gender']=='M', 1, 0)
data_sel['Attrition_Flag'] = le.fit_transform(data_sel['Attrition_Flag'])
data_sel['Education_Level'] = le.fit_transform(data_sel['Education_Level'])
data_sel['Marital_Status'] = le.fit_transform(data_sel['Marital_Status'])
data_sel['Income_Category'] = le.fit_transform(data_sel['Income_Category'])
data_sel['Card_Category'] = le.fit_transform(data_sel['Card_Category'])
data_sel

,CLIENTNUM,Attrition_Flag,Customer_Age,Gender,Dependent_count,Education_Level,Marital_Status,Income_Category,Card_Category,Months_on_book,...,Credit_Limit,Total_Revolving_Bal,Avg_Open_To_Buy,Total_Amt_Chng_Q4_Q1,Total_Trans_Amt,Total_Trans_Ct,Total_Ct_Chng_Q4_Q1,Avg_Utilization_Ratio,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_1,Naive_Bayes_Classifier_Attrition_Flag_Card_Category_Contacts_Count_12_mon_Dependent_count_Education_Level_Months_Inactive_12_mon_2
0,768805383,1,45,1,3,3,1,2,0,39,...,12691.0,777,11914.0,1.335,1144,42,1.625,0.061,0.000093,0.999910
1,818770008,1,49,0,5,2,2,4,0,44,...,8256.0,864,7392.0,1.541,1291,33,3.714,0.105,0.000057,0.999940
2,713982108,1,51,1,3,2,1,3,0,36,...,3418.0,0,3418.0,2.594,1887,20,2.333,0.000,0.000021,0.999980
3,769911858,1,40,0,4,3,3,4,0,34,...,3313.0,2517,796.0,1.405,1171,20,2.333,0.760,0.000134,0.999870
4,709106358,1,40,1,3,5,1,2,0,21,...,4716.0,0,4716.0,2.175,816,28,2.500,0.000,0.000022,0.999980
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10122,772366833,1,50,1,2,2,2,1,0,40,...,4003.0,1851,2152.0,0.703,15476,117,0.857,0.462,0.000191,0.999810
10123,710638233,0,41,1,2,6,0,1,0,25,...,4277.0,2186,2091.0,0.804,8764,69,0.683,0.511,0.995270,0.004729
10124,716506083,0,44,0,1,3,1,4,0,36,...,5409.0,0,5409.0,0.819,10291,60,0.818,0.000,0.997880,0.002118
10125,717406983,0,30,1,2,2,3,1,0,36,...,5281.0,0,5281.0,0.535,8395,62,0.722,0.000,0.996710,0.003294
10126,714337233,0,43,0,2,2,1,4,3,25,...,10388.0,1961,8427.0,0.703,10294,61,0.649,0.189,0.996620,0.003377

In [5]:
data_sel_class_1 = data_sel[data_sel['Gender'] == 1]
data_sel_class_0 = data_sel[data_sel['Gender'] == 0]
data_sel_class_1_oversampled = data_sel_class_1.sample(n=len(data_sel_class_0), replace=True, random_state=42)
balanced_data_sel = pd.concat([data_sel_class_1_oversampled, data_sel_class_0])

In [6]:
X = balanced_data_sel.loc[:, data_sel.columns != 'Gender']
y = balanced_data_sel['Gender']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42)

In [8]:
lr = LogisticRegression()
lr.fit(X_train, y_train)

LogisticRegression()

In [9]:
lr_prediction = lr.predict(X_test)

In [13]:
print(classification_report(lr_prediction, y_test))

              precision    recall  f1-score   support

           0       0.83      0.64      0.72      2061
           1       0.54      0.77      0.64      1154

    accuracy                           0.68      3215
   macro avg       0.69      0.70      0.68      3215
weighted avg       0.73      0.68      0.69      3215

Из результатов можно сделать вывод, что модель работает хорошо для данного набора данных. В данном случае, значения метрик хорошие, это говорит о том, что классификатор работает хорошо.

Пункт № 2:

In [14]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import precision_score, recall_score, f1_score
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report

In [16]:
data = pd.read_csv('C:\\Users\\ivcbibl13\\Documents\\Jupyter\\BankChurners.csv')
data_sel = data.dropna()

In [17]:
le = LabelEncoder()
data_sel['Gender'] = np.where(data_sel['Gender'] == 'M', 1, 0)
data_sel['Attrition_Flag'] = le.fit_transform(data_sel['Attrition_Flag'])
data_sel['Gender'] = le.fit_transform(data_sel['Gender'])
data_sel['Education_Level'] = le.fit_transform(data_sel['Education_Level'])
data_sel['Marital_Status'] = le.fit_transform(data_sel['Marital_Status'])
data_sel['Income_Category'] = le.fit_transform(data_sel['Income_Category'])
data_sel['Card_Category'] = le.fit_transform(data_sel['Card_Category'])

In [18]:
data_sel_class_1 = data_sel[data_sel['Gender'] == 1]
data_sel_class_0 = data_sel[data_sel['Gender'] == 0]
data_sel_class_1_oversampled = data_sel_class_1.sample(n=len(data_sel_class_0), replace=True, random_state=42)
balanced_data_sel = pd.concat([data_sel_class_1_oversampled, data_sel_class_0])

In [19]:
X = balanced_data_sel.loc[:, data_sel.columns != 'Gender']
y = balanced_data_sel['Gender']
# разбиение на тестовую и обучающую выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [20]:
# обучение модели дерева решений
tree_clf = DecisionTreeClassifier(random_state=42)
tree_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [21]:
# оценка точности модели на тестовой выборке
y_pred = tree_clf.predict(X_test)
precision = precision_score(y_test, y_pred, average='weighted')
recall = recall_score(y_test, y_pred, average='weighted')
f1 = f1_score(y_test, y_pred, average='weighted')
print("Метрики для модели дерева решений:")
print("Precision: ", precision)
print("Recall: ", recall)
print("F1-score: ", f1)

Метрики для модели дерева решений:
Precision:  0.9179945016999244
Recall:  0.9174440298507462
F1-score:  0.9174153017949844

In [22]:
# обучение модели случайного леса с перебором гиперпараметров
param_grid = {'n_estimators': range(10,501,10), 'max_depth': [3, 5, 10, 20]}
rf_clf = RandomForestClassifier(random_state=42)
grid_search = GridSearchCV(rf_clf, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train, y_train)

# вывод лучших параметров и оценка точности модели на тестовой выборке
best_params = grid_search.best_params_
best_score = grid_search.best_score_
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

print("Метрики для модели случайного леса:", best_model)
print("Лучшие параметры: ", best_params)
print("Лучшая точность на кросс-валидации: ", best_score)
print(classification_report(y_test, y_pred))

Метрики для модели случайного леса: RandomForestClassifier(max_depth=20, n_estimators=480, random_state=42)
Лучшие параметры:  {'max_depth': 20, 'n_estimators': 480}
Лучшая точность на кросс-валидации:  0.9337371194518814
              precision    recall  f1-score   support

           0       0.95      0.93      0.94      1071
           1       0.93      0.96      0.94      1073

    accuracy                           0.94      2144
   macro avg       0.94      0.94      0.94      2144
weighted avg       0.94      0.94      0.94      2144